import fs from 'node:fs';
import path from 'node:path';
import { pageSeo, sitemapXml, SITE_ORIGIN } from '../server/seo';
import type { DatabaseSchema } from '../server/db';

// Reads only; never calls the datastore initializer or writes merchant catalog data.
const db: DatabaseSchema = JSON.parse(fs.readFileSync('data/db.json', 'utf8'));
const destination = path.resolve('docs/seo'); fs.mkdirSync(destination, { recursive: true });
const csv = (filename: string, headers: string[], rows: unknown[][]) => fs.writeFileSync(path.join(destination, filename), [headers, ...rows].map(row => row.map(value => `"${String(value ?? '').replace(/"/g, '""')}"`).join(',')).join('\n') + '\n');
const paths = [...sitemapXml(db).matchAll(/<loc>(.*?)<\/loc>/g)].map(match => new URL(match[1]).pathname);
const products = db.products.filter(product => product.status === 'published' && product.visible !== false);
const keyword = (route: string) => route === '/' ? 'GlowWithSH' : route === '/shop' ? 'GlowWithSH skincare products' : route.startsWith('/product/') ? products.find(product => `/product/${product.slug}` === route)?.name || 'GlowWithSH product' : route.startsWith('/shop/category/') ? `${db.categories.find(category => `/shop/category/${category.slug}` === route)?.name} online India` : pageSeo(route, db).h1;
const type = (route: string) => route === '/' ? 'Homepage' : route.startsWith('/product/') ? 'Product' : route.startsWith('/shop/category/') ? 'Category' : route.startsWith('/journal/') ? 'Article' : route.startsWith('/policies/') ? 'Policy' : 'Brand / navigation';
const allLinks = new Map(paths.map(route => [route, [...pageSeo(route, db).content.matchAll(/href="([^"]+)"/g)].map(match => match[1])]));
const risks = (route: string) => /tinted-day-cream|anti-acne-gel/.test(route) ? 'High: duplicate names/sizes; distinct SKU metadata implemented; owner must verify whether variants or duplicate listings' : route.startsWith('/product/') ? 'Product intent distinguished from category; existing efficacy/ingredient claims require owner substantiation' : 'No exact duplicate target in this map; rankings unavailable';
csv('keyword-map.csv', ['URL','Page Type','Current Topic','Primary Keyword','Secondary Keywords','Search Intent','Current Title','Recommended Title','Current H1','Recommended H1','Meta Description','Internal Links In','Internal Links Out','Schema','Cannibalization Risk','Content Action'], paths.map(route => {
  const seo = pageSeo(route, db); return [seo.canonical, type(route), seo.h1, keyword(route), `${keyword(route)} price; GlowWithSH`, type(route) === 'Product' ? 'Transactional' : type(route) === 'Category' ? 'Commercial comparison' : 'Navigational / informational', 'Baseline initial HTML reused generic site title; client title differed by route', seo.title, 'Baseline varies by client route; not all independently recorded', seo.h1, seo.description, paths.filter(source => allLinks.get(source)?.includes(route)).map(source => SITE_ORIGIN + source).join(' | '), allLinks.get(route)?.join(' | '), seo.schema.map(value => value['@type']).join(' | '), risks(route), 'Implemented metadata + initial HTML; see content-changelog for exact scope; preserve merchant data'];
}));
csv('page-audit.csv', ['URL','Page Type','HTTP Status','Indexability','Canonical','Title','Description','H1','Primary Keyword','Intent','Content','Internal Links','Schema','Images','Performance','Required Action','Evidence Scope'], [...paths, '/cart','/checkout','/admin','/wishlist','/track-order','/quiz','/nonexistent-audit-page'].map(route => {
  const seo = pageSeo(route, db); return [seo.canonical,type(route),seo.status,seo.index ? 'index,follow' : 'noindex,follow',seo.canonical,seo.title,seo.description,seo.h1,keyword(route),'See keyword-map','Initial HTML content + client interface; policy initial HTML is summary',allLinks.get(route)?.join(' | ') || '',seo.schema.map(value => value['@type']).join(' | '),seo.image || '',route === '/' ? 'Responsive poster 35.8 kB at 640px; no field CWV available' : 'No per-page field CWV available',risks(route),'Local merchant snapshot; generated metadata; real HTTP sitemap routes independently tested; NOT live deployment audit'];
}));
const research: unknown[][] = [];
const add = (term: string, intent: string, stage: string, cluster: string, url: string, branded = false, note = '') => research.push([term,intent,stage,cluster,'India',branded ? 'Brand' : 'Non-brand','Directional only: unmeasured; broad non-brand likely more competitive','No Keyword Planner / GSC / paid SEO metrics access',SITE_ORIGIN+url,'','Unverified','Qualitative priority: branded/product first; broad category next',note]);
add('GlowWithSH','Navigational','Decision','Brand','/',true);
add('GlowWithSH Shagufi Hussain','Navigational','Decision','Founder','/founder',true);
add('GlowWithSH products price','Transactional','Decision','Catalog','/shop',true);
for (const category of db.categories) add(`${category.name.toLowerCase()} online India`,'Commercial','Consideration',category.name,`/shop/category/${category.slug}`,false,'Qualitative intent hypothesis, not measured search demand');
for (const product of products) {
  add(`GlowWithSH ${product.name} price`,'Transactional','Decision',product.categoryName,`/product/${product.slug}`,true,'Catalog name retained; do not turn whitening/acne/SPF names into unsupported efficacy claims');
  add(`${product.name} online India`,'Transactional','Decision',product.categoryName,`/product/${product.slug}`,false,'Product-name hypothesis; claims/label evidence required');
}
add('how to compare skincare serums','Informational','Awareness','Serums','/journal',false,'Future fact-reviewed guide; do not imply ingredient percentages without labels');
add('day cream vs night cream','Informational','Awareness','Creams','/journal',false,'Future general educational guide; each product suitability requires verified directions');
add('skincare routine before wedding','Informational','Awareness','Bridal','/journal',false,'Future practical planning guide; no promised timeline or guaranteed results');
csv('keyword-research.csv',['Keyword','Intent','Funnel Stage','Topic Cluster','Target Market','Brand/Non-brand','Estimated Competition','Verified Metrics Source','Primary URL','Secondary URL','Current Ranking','Opportunity','Notes'],research);
fs.writeFileSync(path.join(destination,'content-changelog.md'), `# Content changes — 2026-10-03\n\nScope: local repository; public catalog snapshot, not production data replacement.\n\n- Homepage: brand/product-type title and description; crawlable category/product links; truthful Organization/WebSite markup. Existing CMS hero wording retained.\n- /about: rewritten brand introduction, comparison guidance and three values; removed unsupported manufacturing/dermatology/cruelty-free storytelling. Founder name retained.\n- /shop and each category: distinct H1/title/description; choosing-products section and support/shipping/returns links; filters remain interactive.\n- Every published product below: unique title/description based on stored name/size/price, SKU disambiguation for duplicate name/size; initial product detail/usage content; neutral Before ordering section; real Product/Offer markup with no invented ratings. Removed hardcoded studio inspection and dispatch/delivery/notification promises from product template. Known stock photos are labelled illustrative and omitted from Product image markup. Unsubstantiated bestseller/new/limited badges are replaced by Featured; review wording distinguishes moderation from purchase verification. Existing merchant descriptions/ingredients/benefits were not independently substantiated or overwritten.\n- /contact and /checkout: clearer support/payment text, labelled fields and error alerts. No fake fallback coupon acceptance.\n- Journal articles: unique metadata/Article markup and existing text in initial HTML. Articles were NOT rewritten into invented ingredient facts.\n- Policies/founder/awards/custom pages: metadata/rendering added; no claim that their business facts or full policy wording have been rewritten or legally approved.\n\n## Exact public URLs receiving metadata/initial HTML\n\n${paths.map(route => `- ${SITE_ORIGIN}${route}`).join('\n')}\n\n## Product template additions apply to\n\n${products.map(product => `- ${SITE_ORIGIN}/product/${product.slug}`).join('\n')}\n\nReasons: separate intent, remove generic titles, expose public navigation before JavaScript, provide purchase information without manufacturing medical claims. No claim of rankings, certified formulations or rich-result eligibility.\n`);
console.log(`SEO audit generated for ${paths.length} public URLs, ${products.length} products, ${research.length} qualitative keyword candidates.`);
